image: amazon/aws-sam-cli-build-image-nodejs14.x:latest
 
stages:
  - deploy

variables:
  STACK_NAME: {{project_slug}}
  REGION: eu-west-2

before_script:
  - set AWS_ACCESS_KEY_ID=$prod_key_id
  - set AWS_SECRET_ACCESS_KEY=$prod_secret_key

deploy:
  image: amazon/aws-sam-cli-build-image-nodejs14.x:latest
  stage: deploy
  script:
   - sam build
   - sam package --output-template-file packaged.yaml --s3-bucket gitlab-codebucket --region $REGION
   - sam deploy --no-fail-on-empty-changeset --template-file packaged.yaml --stack-name $STACK_NAME --s3-bucket gitlab-codebucket --capabilities CAPABILITY_NAMED_IAM --region $REGION --parameter-overrides TargetEnvironment=prod
